# Generated by Django 2.2.16 on 2022-10-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': ('записи', 'Авторы', 'посты')},
        ),
    ]
